[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = 'source $NVIM_CONFIG_DIR/plugins/deoplete/hook_source.vim'
build = 'pip install pynvim'
on_i = 1

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
on_i = 1
 
[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_source = 'source $NVIM_CONFIG_DIR/plugins/neosnippet/hook_source.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
depends = 'neosnippet.vim'
on_i = 1

# [[plugins]]
# repo  = 'mtscout6/syntastic-local-eslint.vim'
# on_ft = ['javascript', 'typescript', 'typescriptreact']
# 
[[plugins]]
repo  = 'prettier/vim-prettier'
build = 'yarn install'
on_ft = ['javascript', 'typescript', 'typescriptreact', 'vue', 'css', 'sass', 'scss', 'json', 'markdown']
hook_source = '''
let g:tigris#enabled = 1
let g:tigris#autoformat = 1
let g:tigris#on_the_fly_enabled = 1
let g:tigris#delay = 300
autocmd BufWritePre *.js,*.ts,*.tsx,*.vue,*.css,*.scss,*.json,*.md PrettierAsync
'''

[[plugins]]
repo  = 'mattn/emmet-vim'
on_ft = ['htm', 'html', 'css']
hook_source = 'source $DOTVIM_DIR/plugins/emmet/hook_source.vim'

[[plugins]] # toml syntax
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # ps1 syntax
repo  = 'PProvost/vim-ps1'
on_ft = 'ps1'

[[plugins]] # kotlin syntax
repo  = 'udalov/kotlin-vim'
on_ft = 'kt'

[[plugins]] # typescript syntax
repo    = 'leafgarland/typescript-vim'
on_ft   = 'typescript'

[[plugins]] # typescriptreact syntax
repo  = 'peitalin/vim-jsx-typescript'
on_ft = 'typescriptreact'

[[plugins]] # rust syntax highlight, formattingm syntastic integration, ...
repo    = 'rust-lang/rust.vim'
on_ft   = 'rust'
hook_source = 'source $NVIM_CONFIG_DIR/plugins/rust.vim/hook_source.vim'
depends = 'syntastic'

[[plugins]]
repo  = 'fatih/vim-go'
on_ft = 'go'
hook_post_update = 'GoUpdateBinaries'
hook_source = 'source $NVIM_CONFIG_DIR/plugins/vim-go/hook_source.vim'

# [[plugins]]
# repo  = 'karanokuri/previm'
# rev   = 'feature/add-plantuml-plugin'
# on_ft = 'markdown'
# depends = 'open-browser.vim'

# [[plugins]]
# repo = 'tyru/open-browser.vim'
