memodir = "$USERPROFILE/.memo"
editor = "nvim-qt.exe"
column = 20
width = 0
selectcmd = "peco"
grepcmd = "grep -nH ${PATTERN} ${FILES}"
memotemplate = "$KARANOENV/setup/memo/template.md"
assetsdir = "."
pluginsdir = "$KARANOENV/setup/memo/plugins"
templatedirfile = ""
templatebodyfile = ""
