[[plugins]]
repo = 'Shougo/dein.vim'
hook_post_update = '''
let g:dein#plugin.build = g:python3_host_prog . " -m pip install --user --upgrade pynvim"
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'pepo-le/win-ime-con.nvim'
hook_add = '''let g:win_ime_con_mode = 0'''

[[plugins]]
repo = 'sheerun/vim-wombat-scheme'
hook_add = '''au VimEnter * nested colorscheme wombat'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'
hook_add = 'source $NVIM_CONFIG_DIR/plugins/vim-precious/hook_add.vim'

[[plugins]]
repo = 'windwp/nvim-autopairs'
on_event = 'InsertEnter'
hook_source = '''lua require('nvim-autopairs').setup{}'''

[[plugins]]
repo = 'mattn/vim-sonictemplate'
hook_add = 'source $NVIM_CONFIG_DIR/plugins/vim-sonictemplate/hook_add.vim'

[[plugins]]
repo = 'Shougo/deol.nvim'
hook_add = 'nnoremap <silent><Leader>t :<C-u>Deol -command=nyagos -split=floating -winheight=35<CR>'

###############################################################################
# snippets

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_event = 'InsertEnter'

###############################################################################
# git

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'source $NVIM_CONFIG_DIR/plugins/vim-gitgutter/hook_add.vim'

###############################################################################
# lightline

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source $NVIM_CONFIG_DIR/plugins/lightline/hook_add.vim'

[[plugins]]
repo = 'josa42/nvim-lightline-lsp'
hook_add = '''
let g:lightline#lsp#indicator_errors = '× '
call lightline#lsp#register()
'''

###############################################################################
# syntax

[[plugins]] # toml syntax
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # ps1 syntax
repo  = 'PProvost/vim-ps1'
on_ft = 'ps1'

[[plugins]] # kotlin syntax
repo  = 'udalov/kotlin-vim'
on_ft = 'kt'

[[plugins]] # typescript syntax
repo    = 'leafgarland/typescript-vim'
on_ft   = ['typescript', 'typescriptreact']

[[plugins]] # typescriptreact syntax
repo  = 'peitalin/vim-jsx-typescript'
on_ft = 'typescriptreact'

[[plugins]] # rust syntax highlight, formatting, syntastic integration, ...
repo    = 'rust-lang/rust.vim'
on_ft   = 'rust'
hook_source = 'source $NVIM_CONFIG_DIR/plugins/rust.vim/hook_source.vim'

[[plugins]]
repo  = 'fatih/vim-go'
on_ft = 'go'
hook_post_update = 'GoUpdateBinaries'
hook_source = 'source $NVIM_CONFIG_DIR/plugins/vim-go/hook_source.vim'

[[plugins]]
repo  = 'ElmCast/elm-vim'
on_ft = 'elm'
hook_source = '''let g:elm_format_autosave = 1'''

[[plugins]]
repo = 'karanokuri/vim-firestore'
rev  = 'fix-encoding'

###############################################################################
# lsp

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = 'source $NVIM_CONFIG_DIR/plugins/vim-lsp/hook_add.vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = 'vim-lsp'
hook_add = 'source $NVIM_CONFIG_DIR/plugins/vim-lsp-settings/hook_add.vim'

###############################################################################
# ddc

[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = 'InsertEnter'
hook_source = 'source $NVIM_CONFIG_DIR/plugins/ddc.vim/hook_source.vim'

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'LumaKernel/ddc-file'
on_source = 'ddc.vim'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
on_source = 'ddc.vim'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_source = 'ddc.vim'

[[plugins]]
repo = 'shun/ddc-vim-lsp'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/deoppet.nvim'
on_source = ['ddc.vim', 'neosnippet.vim']
hook_source = 'source $NVIM_CONFIG_DIR/plugins/deoppet.nvim/hook_source.vim'
