[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimshell'
hook_add = 'source $DOTVIM_DIR/plugins/vimshell/hook_add.vim'

[[plugins]]
repo = 'sheerun/vim-wombat-scheme'
hook_add = '''au VimEnter * nested colorscheme wombat'''

[[plugins]]
repo = 'vim-syntastic/syntastic'
hook_add = 'source $DOTVIM_DIR/plugins/syntastic/hook_add.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source $DOTVIM_DIR/plugins/lightline/hook_add.vim'

[[plugins]]
repo = 'MetalPhaeton/easybracket-vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'source $DOTVIM_DIR/plugins/vim-gitgutter/hook_add.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = 'source $DOTVIM_DIR/plugins/coc.nvim/hook_add.vim'

[[plugins]]
repo = 'neoclide/coc-snippets'
build = 'yarn install --frozen-lockfile'
hook_add = 'source $DOTVIM_DIR/plugins/coc-snippets/hook_add.vim'
depends = 'coc.nvim'
